os: osx
# These represent OS X 10.12 - 10.15.
# Extra matrix entries add OS X 10.10 - 10.11.
osx_image:
  - xcode12.2 # 10.15
  - xcode10.2 # 10.14
  - xcode10 # 10.13
  - xcode9.2 # 10.12
branches:
  only:
    - master
env:
  global:
    - HOMEBREW_LOGS=~/homebrew-logs
    - HOMEBREW_TEMP=~/homebrew-temp
    - HOMEBREW_NO_AUTO_UPDATE=1
  matrix:
    - CASK=pe-client-tools
    - CASK=pe-client-tools-2019.3
    - CASK=pe-client-tools-2018.1
    - CASK=pdk
    - CASK=puppet-agent
    - CASK=puppet-agent-5
    - CASK=puppet-agent-6
    - CASK=puppet-agent-7
    - CASK=puppet-bolt
script:
  - brew cask install Casks/$CASK.rb --force
matrix:
  include:
    - osx_image: xcode9.2
      env: CASK=pe-client-tools
    - osx_image: xcode10.1
      env: CASK=pe-client-tools
    - osx_image: xcode11.1
      env: CASK=pe-client-tools
    - osx_image: xcode8
      env: CASK=pdk
    - osx_image: xcode6.4
      env: CASK=puppet-agent-5
    - osx_image: xcode8
      env: CASK=puppet-agent-5
    - osx_image: xcode8
      env: CASK=puppet-bolt
    - osx_image: xcode10.2
      env: FORMULA=wash
      script: brew install Formula/$FORMULA.rb
    - osx_image: xcode10.2
      env: FORMULA=relay
      script: brew install Formula/$FORMULA.rb
  exclude:
    - osx_image: xcode9.2
      env: CASK=puppet-agent-7
    - osx_image: xcode10
      env: CASK=puppet-agent-7
    - osx_image: xcode9.2
      env: CASK=puppet-agent
    - osx_image: xcode10
      env: CASK=puppet-agent
